#! /usr/bin/perl

use Settings;

my $base  = "http://www.ncdc.noaa.gov/cdo-services/services";
my $token = $Settings::token;

sub sys {
    my $cmd = shift;
    print $cmd, "\n";
    return system($cmd);
}

sub xml_request {
    my $file = shift;
    my $path = shift;
    my $args = shift;
    if ($args) {
        $args = "&" . $args;
    }
    sys(sprintf("curl '%s/%s.xml?token=$token$args' | xmllint --format - > %s", $base, $path, $file));
}

# List of all datasets:
#xml_request("datasets.xml",                         "datasets");

# Details of a particular dataset (GHCND):
#xml_request("ghcnd.xml",                            "datasets/GHCND");

# List of variables (datatypes) in the GHCND dataset:
#xml_request("ghcnd-datatypes.xml",                  "datasets/GHCND/datatypes");

# List stations within GHCN-Daily (100 Stations per page limit):
#xml_request("ghcnd-stations1.xml",                  "datasets/GHCND/stations",  "page=1");

# List of location types for a particular dataset (GHCND):
#xml_request("ghcnd-location-types.xml",                  "datasets/GHCND/locationtypes");

# List of locations of a particular type (CNTRY) for a particular dataset (GHCND):
#xml_request("ghcnd-cntry-locations1.xml",                  "datasets/GHCND/locationtypes/CNTRY/locations", "page=1");
#xml_request("ghcnd-cntry-locations2.xml",                  "datasets/GHCND/locationtypes/CNTRY/locations", "page=2");

# List stations within FIPS:US location in GHCN-Daily (100 Stations per page limit):
#for ($i=11; $i<=461; ++$i) {
#    $p = sprintf("%03d", $i);
#    xml_request("ghcnd-us-stations$p.xml",                  "datasets/GHCND/locations/FIPS:US/stations", "page=$i");
#    sleep(1);
#}

@ids = ();
open(IN, "<ghcnd-us-stations.txt");
while (<IN>) {
    chomp;
    if (/\S/) {
        push(@ids, $_);
    }
}
close(IN);
printf("read %1d ids\n", (@ids+0));
#unlink("ghcnd-us-stations-datatypes.xml");
open(OUT, ">>ghcnd-us-stations-datatypes.xml");
print OUT "<stationsDataTypes>\n";
close(OUT);
for ($i=$#ids; $i<=$#ids; ++$i) {
    # List of datatypes available for a given station:
    #xml_request("ghcnd-ca001165793-datatypes.xml",      "datasets/GHCND/stations/GHCND:CA001165793/datatypes");
    $id = $ids[$i];
    sleep(1);
    xml_request("foo.xml",      "datasets/GHCND/stations/$id/datatypes");
    open(OUT, ">>ghcnd-us-stations-datatypes.xml");
    printf(OUT "<datatypes stationid=\"%s\">\n", $id);
    open(IN, "<foo.xml");
    while (<IN>) {
    if (/xml version="1.0" encoding="UTF-8" standalone="yes"/) {
        # omit this line
    } else {
        print OUT $_;
    }
    close(IN);
    printf(OUT "</datatypes>\n");
    close(OUT);
    unlink("foo.xml");
}
open(OUT, ">>ghcnd-us-stations-datatypes.xml");
print OUT "</stationsDataTypes>\n";
close(OUT);


# Displays info about a particular data type from a given station (subset of above?):
# xml_request("tmax.xml",      "datasets/GHCND/stations/GHCND:CA001165793/datatypes/TMAX");

# http://www.ncdc.noaa.gov/cdo-services/services/datasets/GHCND/locations/FIPS:AS/data?year=2001&month=1
