#! /usr/bin/perl

use XML::Parser::PerlSAX;

my $datatypes = {};

my $my_handler = MyHandler->new;
$parser = XML::Parser::PerlSAX->new( Handler => $my_handler );

$filename = 'ghcnd-datatypes.xml';
$parser->parse(Source => { SystemId => $filename });

foreach $id (keys(%{$datatypes})) {
    printf("%s: %s\n", $id, $datatypes->{$id});
}

########################################################################

package MyHandler;

my $id;
my $description;

sub new {
    my ($type) = @_;
    return bless {}, $type;
}

sub start_element {
    my ($self, $element) = @_;
    my %attr = %{$element->{Attributes}};

    $current_chars = '';
}

sub end_element {
    my ($self, $element) = @_;

    if ($element->{Name} eq "id") {
        $id = $current_chars;
    }
    elsif ($element->{Name} eq "description") {
        $description = $current_chars;
    }
    elsif ($element->{Name} eq "dataType") {
        $datatypes->{$id} = $description;
    }
}

sub characters {
    my ($self, $characters) = @_;
    my $text = $characters->{Data};

    $current_chars .= $characters->{Data};
}
